api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = ".NET SDK Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "4c347c269189d3f6ff7321e505a4667f8c5fac2fcfb08a1d29f1f38d712f60c6"
    source = "https://download.visualstudio.microsoft.com/download/pr/9ba4d9b0-3fca-40ed-b5a2-1552dfa4f89e/8e5e555b543a7afd8fd764e080d25671/dotnet-sdk-2.1.804-linux-x64.tar.gz"
    source_sha256 = "51ce9fe209ed1ba5b077021fd23694808291ff8cf90dc56f04912b8cab9cb510"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.804.linux-amd64-any-stack-4c347c26.tar.xz"
    version = "2.1.804"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "20bb1ae296012d3db829cbbe5574beb2b27139546e2673b0d8414d6a8c556d2b"
    source = "https://download.visualstudio.microsoft.com/download/pr/e730fe40-e2ea-42e5-a5d0-f86830d75849/571e5a2f4ebf9f8117878eeaad5cb19b/dotnet-sdk-2.1.805-linux-x64.tar.gz"
    source_sha256 = "af5241c99f58ddf26b4b934d681750fbe5da4245d5e528eb88a6e2c78ef54cde"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.805_linux_x64_any-stack_20bb1ae2.tar.xz"
    version = "2.1.805"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "5f665939a6d9a6218fd98b24142f44ebee5387361dd871a4ad7659587f815f27"
    source = "https://download.visualstudio.microsoft.com/download/pr/daec2daf-b458-4ae1-9046-b8ba09b5fb49/733e2d73b41640d6e6bdf1cc6b9ef03b/dotnet-sdk-3.1.200-linux-x64.tar.gz"
    source_sha256 = "eca308c601e5d611af8203ac8d5aeb216a65a1038ac7238b6fcbed126ed54bde"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.200_linux_x64_any-stack_5f665939.tar.xz"
    version = "3.1.200"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "1904ac7d51d4680c1a123500f67e5cac86ea960f26676abab9e17e56b125d17a"
    source = "https://download.visualstudio.microsoft.com/download/pr/f65a8eb0-4537-4e69-8ff3-1a80a80d9341/cc0ca9ff8b9634f3d9780ec5915c1c66/dotnet-sdk-3.1.201-linux-x64.tar.gz"
    source_sha256 = "222f5363d2ab9f2aa852846bc0745c449677d1cccf8c8407cd0a44d3299cc7be"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.201_linux_x64_any-stack_1904ac7d.tar.xz"
    version = "3.1.201"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a3b769a0ca981d62287e2a402eda79754d2c64a0e00eda66f06e2c093735d9c3"
    source = "https://download.visualstudio.microsoft.com/download/pr/7d4c708b-38db-48b2-8532-9fc8a3ab0e42/23229fd17482119822bd9261b3570d87/dotnet-sdk-3.1.202-linux-x64.tar.gz"
    source_sha256 = "835ecc219be32036f0e91fce7e9c1eeda1609ee26dc2b6089506b436af4a7fc3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.202_linux_x64_any-stack_a3b769a0.tar.xz"
    version = "3.1.202"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.16"
    sdks = ["2.1.804"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.17"
    sdks = ["2.1.805"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.2"
    sdks = ["3.1.200"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.3"
    sdks = ["3.1.201"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
