api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.default-versions]
	  dotnet-sdk = "5.*"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "150ea1e3eea5d4559728c5df14e4bdfcf30bace7c16c385322892f0042f190f5"
    source = "https://download.visualstudio.microsoft.com/download/pr/4281b67c-db32-4e7e-aa67-976a59839b81/75373c7621c37c2ac7a83fc60d415afd/dotnet-sdk-2.1.811-linux-x64.tar.gz"
    source_sha256 = "687a33b25da47ec2f97dccd202c0f286bfbf55743a91e54a54aabd8b601fcf4a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.811_linux_x64_any-stack_150ea1e3.tar.xz"
    version = "2.1.811"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "5ead72ec6566910e493ccb3bf5d688f40861db9d50baf3cfaa13c9956d136ef9"
    source = "https://download.visualstudio.microsoft.com/download/pr/98903dda-7825-47af-9699-ac44f7f92cb6/7b5b7d7498bd2bc104510c14cb03342d/dotnet-sdk-2.1.812-linux-x64.tar.gz"
    source_sha256 = "98b306edbe4c1e6830085158117bb9680304709d6fca9a1c8e3b6db5274ecdce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.812_linux_x64_any-stack_5ead72ec.tar.xz"
    version = "2.1.812"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "c0b6b74b7c475e37d4bf196c5ce8989b538686e5fc294615f3e39ce37a2e984a"
    source = "https://download.visualstudio.microsoft.com/download/pr/ec187f12-929e-4aa7-8abc-2f52e147af1d/56b0dbb5da1c191bff2c271fcd6e6394/dotnet-sdk-3.1.404-linux-x64.tar.gz"
    source_sha256 = "6b8dd87de54bd855968325feec9cf57e2fb4b0dba745591d48d71eb2b8d7280d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.404_linux_x64_any-stack_c0b6b74b.tar.xz"
    version = "3.1.404"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a60f3aaf910371ec56a1d32b6a1211e2ec8926742e31652acf40e61556b1a711"
    source = "https://download.visualstudio.microsoft.com/download/pr/5de23f6d-648c-455b-a7a9-d11c9a5bca40/4836262466f2d288e8ad8647944d062f/dotnet-sdk-3.1.405-linux-x64.tar.gz"
    source_sha256 = "28105c86ae24c12379b09a60c992e2f0daecea58cdd2ffa6a2e541fe26bf0661"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.405_linux_x64_any-stack_a60f3aaf.tar.xz"
    version = "3.1.405"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "1cc4e57c70727149d1772b90be1ace8134c2ac138b210425c909199ca98c9536"
    source = "https://download.visualstudio.microsoft.com/download/pr/a0487784-534a-4912-a4dd-017382083865/be16057043a8f7b6f08c902dc48dd677/dotnet-sdk-5.0.101-linux-x64.tar.gz"
    source_sha256 = "23df1eca7eb1302dfb10f4edce7edf7150e57698576f61b2dcb777c833cbd80c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.101_linux_x64_any-stack_1cc4e57c.tar.xz"
    version = "5.0.101"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a85dd2bdde1abb544d9c4d32ce0fd2f7fbc8ed21112c49269fa8cd13e99d2b92"
    source = "https://download.visualstudio.microsoft.com/download/pr/7f736160-9f34-4595-8d72-13630c437aef/b9c4513afb0f8872eb95793c70ac52f6/dotnet-sdk-5.0.102-linux-x64.tar.gz"
    source_sha256 = "4bb7f951750e87dffdbca5ee21d13b11e2db7f7e37045e84cd6052ff1fadd0aa"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.102_linux_x64_any-stack_a85dd2bd.tar.xz"
    version = "5.0.102"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.23"
    sdks = ["2.1.811"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.24"
    sdks = ["2.1.812"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.10"
    sdks = ["3.1.404"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.11"
    sdks = ["3.1.405"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.1"
    sdks = ["5.0.101"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.2"
    sdks = ["5.0.102"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
