api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "fde667012629b99f2e093caf736e2a8b50dc3206e1062a2622abb526d1ea08b6"
    source = "https://download.visualstudio.microsoft.com/download/pr/eb1b19f5-3c42-4f7b-b36a-67fae2040506/40cc70f95b6485b0b87bcbc655b7c855/dotnet-sdk-2.1.810-linux-x64.tar.gz"
    source_sha256 = "3856c888ed777818f6e4fb38434adbd139abd0cd4512c0579847503238987b65"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.810_linux_x64_any-stack_fde66701.tar.xz"
    version = "2.1.810"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "150ea1e3eea5d4559728c5df14e4bdfcf30bace7c16c385322892f0042f190f5"
    source = "https://download.visualstudio.microsoft.com/download/pr/4281b67c-db32-4e7e-aa67-976a59839b81/75373c7621c37c2ac7a83fc60d415afd/dotnet-sdk-2.1.811-linux-x64.tar.gz"
    source_sha256 = "687a33b25da47ec2f97dccd202c0f286bfbf55743a91e54a54aabd8b601fcf4a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.811_linux_x64_any-stack_150ea1e3.tar.xz"
    version = "2.1.811"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "94ec0b48b052227519386233aeb84521440753951bbba6713702918bf6d71012"
    source = "https://download.visualstudio.microsoft.com/download/pr/4f9b8a64-5e09-456c-a087-527cfc8b4cd2/15e14ec06eab947432de139f172f7a98/dotnet-sdk-3.1.401-linux-x64.tar.gz"
    source_sha256 = "292d8f5694df7560c39a16c12d5b5efa4038c0973d1adb768f90f39982da1c43"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.401_linux_x64_any-stack_94ec0b48.tar.xz"
    version = "3.1.401"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "e0aedde79c13a4a58e0fb85dc7d12fe005675a4214bec009680d412981ece15a"
    source = "https://download.visualstudio.microsoft.com/download/pr/f01e3d97-c1c3-4635-bc77-0c893be36820/6ec6acabc22468c6cc68b61625b14a7d/dotnet-sdk-3.1.402-linux-x64.tar.gz"
    source_sha256 = "2b6b172f9483e499141e37a6b932a547d9476bf03f3e71a0fefb76c52e01a9ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.402_linux_x64_any-stack_e0aedde7.tar.xz"
    version = "3.1.402"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.22"
    sdks = ["2.1.810"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.23"
    sdks = ["2.1.811"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.7"
    sdks = ["3.1.401"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.8"
    sdks = ["3.1.402"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
