api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = ".NET SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "20bb1ae296012d3db829cbbe5574beb2b27139546e2673b0d8414d6a8c556d2b"
    source = "https://download.visualstudio.microsoft.com/download/pr/e730fe40-e2ea-42e5-a5d0-f86830d75849/571e5a2f4ebf9f8117878eeaad5cb19b/dotnet-sdk-2.1.805-linux-x64.tar.gz"
    source_sha256 = "af5241c99f58ddf26b4b934d681750fbe5da4245d5e528eb88a6e2c78ef54cde"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.805_linux_x64_any-stack_20bb1ae2.tar.xz"
    version = "2.1.805"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "6f9c29da85a4c8be58023f3bb94100d4a597d7b4ee14477cc32bc7823bae7fb9"
    source = "https://download.visualstudio.microsoft.com/download/pr/490da2e4-8f32-433d-8c2e-dd2a11088acd/cfba2ec3df2dedc2dd060b0f79f44b4e/dotnet-sdk-2.1.806-linux-x64.tar.gz"
    source_sha256 = "82045e5ad60d2f38d642d2adb6091506fffb4b63b119f3dbdc3796515f8bcc76"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.806_linux_x64_any-stack_6f9c29da.tar.xz"
    version = "2.1.806"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a3b769a0ca981d62287e2a402eda79754d2c64a0e00eda66f06e2c093735d9c3"
    source = "https://download.visualstudio.microsoft.com/download/pr/7d4c708b-38db-48b2-8532-9fc8a3ab0e42/23229fd17482119822bd9261b3570d87/dotnet-sdk-3.1.202-linux-x64.tar.gz"
    source_sha256 = "835ecc219be32036f0e91fce7e9c1eeda1609ee26dc2b6089506b436af4a7fc3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.202_linux_x64_any-stack_a3b769a0.tar.xz"
    version = "3.1.202"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "16dab4ef7d91eb29a69cfe15a51b51d70d58604c957c686d28eac5c1f3ce3d32"
    source = "https://download.visualstudio.microsoft.com/download/pr/8db2b522-7fa2-4903-97ec-d6d04d297a01/f467006b9098c2de256e40d2e2f36fea/dotnet-sdk-3.1.301-linux-x64.tar.gz"
    source_sha256 = "a0c416bb57f7e16a4767e7cd4dbeab80386fffc354ee7cdc68d367694bc40269"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.301_linux_x64_any-stack_16dab4ef.tar.xz"
    version = "3.1.301"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.17"
    sdks = ["2.1.805"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.18"
    sdks = ["2.1.806"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.4"
    sdks = ["3.1.202"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.5"
    sdks = ["3.1.301"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
