api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET Core SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-sdk = "5.*"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "5ead72ec6566910e493ccb3bf5d688f40861db9d50baf3cfaa13c9956d136ef9"
    source = "https://download.visualstudio.microsoft.com/download/pr/98903dda-7825-47af-9699-ac44f7f92cb6/7b5b7d7498bd2bc104510c14cb03342d/dotnet-sdk-2.1.812-linux-x64.tar.gz"
    source_sha256 = "98b306edbe4c1e6830085158117bb9680304709d6fca9a1c8e3b6db5274ecdce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.812_linux_x64_any-stack_5ead72ec.tar.xz"
    version = "2.1.812"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "8f9246c099362d8db7b79660b417d0ccb35e950bab3835534f90c8c14c9b778e"
    source = "https://download.visualstudio.microsoft.com/download/pr/e1883c23-aad6-4658-a0bf-cdfb3d430d26/a2b8bdd775b9f5b1ff3424463955001c/dotnet-sdk-2.1.813-linux-x64.tar.gz"
    source_sha256 = "75075c795104798ed8e57f3843238275c463f5537da919413da956ad77e898ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.813_linux_x64_any-stack_8f9246c0.tar.xz"
    version = "2.1.813"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "c0b6b74b7c475e37d4bf196c5ce8989b538686e5fc294615f3e39ce37a2e984a"
    source = "https://download.visualstudio.microsoft.com/download/pr/ec187f12-929e-4aa7-8abc-2f52e147af1d/56b0dbb5da1c191bff2c271fcd6e6394/dotnet-sdk-3.1.404-linux-x64.tar.gz"
    source_sha256 = "6b8dd87de54bd855968325feec9cf57e2fb4b0dba745591d48d71eb2b8d7280d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.404_linux_x64_any-stack_c0b6b74b.tar.xz"
    version = "3.1.404"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a60f3aaf910371ec56a1d32b6a1211e2ec8926742e31652acf40e61556b1a711"
    source = "https://download.visualstudio.microsoft.com/download/pr/5de23f6d-648c-455b-a7a9-d11c9a5bca40/4836262466f2d288e8ad8647944d062f/dotnet-sdk-3.1.405-linux-x64.tar.gz"
    source_sha256 = "28105c86ae24c12379b09a60c992e2f0daecea58cdd2ffa6a2e541fe26bf0661"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.405_linux_x64_any-stack_a60f3aaf.tar.xz"
    version = "3.1.405"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a85dd2bdde1abb544d9c4d32ce0fd2f7fbc8ed21112c49269fa8cd13e99d2b92"
    source = "https://download.visualstudio.microsoft.com/download/pr/7f736160-9f34-4595-8d72-13630c437aef/b9c4513afb0f8872eb95793c70ac52f6/dotnet-sdk-5.0.102-linux-x64.tar.gz"
    source_sha256 = "4bb7f951750e87dffdbca5ee21d13b11e2db7f7e37045e84cd6052ff1fadd0aa"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.102_linux_x64_any-stack_a85dd2bd.tar.xz"
    version = "5.0.102"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a49f6f5de8a4e20fbd48e15a729f735ee562d56d20765db3e3ba80f1c30474a5"
    source = "https://download.visualstudio.microsoft.com/download/pr/a2052604-de46-4cd4-8256-9bc222537d32/a798771950904eaf91c0c37c58f516e1/dotnet-sdk-5.0.103-linux-x64.tar.gz"
    source_sha256 = "bfcba3fe957949ac79170a9a6ddcf18403469ea39b4cfb6c2226178f138196d9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.103_linux_x64_any-stack_a49f6f5d.tar.xz"
    version = "5.0.103"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.24"
    sdks = ["2.1.812"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.25"
    sdks = ["2.1.813"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.10"
    sdks = ["3.1.404"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.11"
    sdks = ["3.1.405"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.2"
    sdks = ["5.0.102"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.3"
    sdks = ["5.0.103"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
