api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET Core SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-sdk = "5.*"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "8f9246c099362d8db7b79660b417d0ccb35e950bab3835534f90c8c14c9b778e"
    source = "https://download.visualstudio.microsoft.com/download/pr/e1883c23-aad6-4658-a0bf-cdfb3d430d26/a2b8bdd775b9f5b1ff3424463955001c/dotnet-sdk-2.1.813-linux-x64.tar.gz"
    source_sha256 = "75075c795104798ed8e57f3843238275c463f5537da919413da956ad77e898ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.813_linux_x64_any-stack_8f9246c0.tar.xz"
    version = "2.1.813"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "75f703fdcc9c4701cdc2419c93c72d80a02926f57fbd7e0fd86aab0cad607a13"
    source = "https://download.visualstudio.microsoft.com/download/pr/b44d40e6-fa23-4f2d-a0a9-4199731f0b1e/5e62077a9e8014d8d4c74aee5406e0c7/dotnet-sdk-2.1.814-linux-x64.tar.gz"
    source_sha256 = "2c16e62f1b19b32f30d56eeaeeb70b89acb4599b7523a20e159204c3741b46f0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.814_linux_x64_any-stack_75f703fd.tar.xz"
    version = "2.1.814"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "8a61800f5eed6c88e0f3addd30dc5d7cb8918500f67c6fa2a842724fe4d950e6"
    source = "https://download.visualstudio.microsoft.com/download/pr/7fba29f6-aac9-4b53-a5f9-9b421bec6288/70ac39be0282331d18b535f64ea5f40a/dotnet-sdk-2.1.815-linux-x64.tar.gz"
    source_sha256 = "72d2630b67c1337aa25285da82d1b0ce5eceb3e6cfabdb12521151fd4508c626"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.815_linux_x64_any-stack_8a61800f.tar.xz"
    version = "2.1.815"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "ee05431441441117af62a7816074cbe22507a10f50d7d51d7e85c3b2057a7c55"
    source = "https://download.visualstudio.microsoft.com/download/pr/d7b8da76-a160-44a1-8038-b4b91404b8f2/af410f6d2e213ef7ee9dfefd853e97c0/dotnet-sdk-3.1.406-linux-x64.tar.gz"
    source_sha256 = "9b436009f36e8e93f4414bfc245ad7c383521d95f80e8f6f12d93428bc186293"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.406_linux_x64_any-stack_ee054314.tar.xz"
    version = "3.1.406"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "d0142171d41b20d5a4e60f312119ff5fde94b9d8b0f54baa0a357104455ff24a"
    source = "https://download.visualstudio.microsoft.com/download/pr/ab82011d-2549-4e23-a8a9-a2b522a31f27/6e615d6177e49c3e874d05ee3566e8bf/dotnet-sdk-3.1.407-linux-x64.tar.gz"
    source_sha256 = "a744359910206fe657c3a02dfa54092f288a44c63c7c86891e866f0678a7e911"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.407_linux_x64_any-stack_d0142171.tar.xz"
    version = "3.1.407"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a6fff94eddb789f130b755ad1aff4b427abbc0660ea410c4df90335235bc2423"
    source = "https://download.visualstudio.microsoft.com/download/pr/73a9cb2a-1acd-4d20-b864-d12797ca3d40/075dbe1dc3bba4aa85ca420167b861b6/dotnet-sdk-5.0.201-linux-x64.tar.gz"
    source_sha256 = "9ff77087831e8ca32719566ec9ef537e136cfc02c5ff565e53f5509cc6e7b341"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.201_linux_x64_any-stack_a6fff94e.tar.xz"
    version = "5.0.201"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "6ff9d3ab2cca769e4dc436569871e031eb87482619be4c0bae212af9e24d758a"
    source = "https://download.visualstudio.microsoft.com/download/pr/5f0f07ab-cd9a-4498-a9f7-67d90d582180/2a3db6698751e6cbb93ec244cb81cc5f/dotnet-sdk-5.0.202-linux-x64.tar.gz"
    source_sha256 = "d2994d4e995bbab003b2d1b137807936fd96c94ba9982822893d62904aab54cf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.202_linux_x64_any-stack_6ff9d3ab.tar.xz"
    version = "5.0.202"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.25"
    sdks = ["2.1.813"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.26"
    sdks = ["2.1.814"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.12"
    sdks = ["3.1.406"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.13"
    sdks = ["3.1.407"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.4"
    sdks = ["5.0.201"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.5"
    sdks = ["5.0.202"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
