api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "fde667012629b99f2e093caf736e2a8b50dc3206e1062a2622abb526d1ea08b6"
    source = "https://download.visualstudio.microsoft.com/download/pr/eb1b19f5-3c42-4f7b-b36a-67fae2040506/40cc70f95b6485b0b87bcbc655b7c855/dotnet-sdk-2.1.810-linux-x64.tar.gz"
    source_sha256 = "3856c888ed777818f6e4fb38434adbd139abd0cd4512c0579847503238987b65"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.810_linux_x64_any-stack_fde66701.tar.xz"
    version = "2.1.810"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "150ea1e3eea5d4559728c5df14e4bdfcf30bace7c16c385322892f0042f190f5"
    source = "https://download.visualstudio.microsoft.com/download/pr/4281b67c-db32-4e7e-aa67-976a59839b81/75373c7621c37c2ac7a83fc60d415afd/dotnet-sdk-2.1.811-linux-x64.tar.gz"
    source_sha256 = "687a33b25da47ec2f97dccd202c0f286bfbf55743a91e54a54aabd8b601fcf4a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.811_linux_x64_any-stack_150ea1e3.tar.xz"
    version = "2.1.811"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "cc16eeb2bec8d22079310b421031cfc6e0c29a5a732d13b877551ea0e1d37b6b"
    source = "https://download.visualstudio.microsoft.com/download/pr/fdd9ecec-56b4-40f4-b762-d7efe24fc3cd/ffef51844c92afa6714528e10609a30f/dotnet-sdk-3.1.403-linux-x64.tar.gz"
    source_sha256 = "a87b3cbc4f1253fb36a879472c1a792d98edd7cad0085aed7855474d121f4c47"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.403_linux_x64_any-stack_cc16eeb2.tar.xz"
    version = "3.1.403"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "c0b6b74b7c475e37d4bf196c5ce8989b538686e5fc294615f3e39ce37a2e984a"
    source = "https://download.visualstudio.microsoft.com/download/pr/ec187f12-929e-4aa7-8abc-2f52e147af1d/56b0dbb5da1c191bff2c271fcd6e6394/dotnet-sdk-3.1.404-linux-x64.tar.gz"
    source_sha256 = "6b8dd87de54bd855968325feec9cf57e2fb4b0dba745591d48d71eb2b8d7280d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.404_linux_x64_any-stack_c0b6b74b.tar.xz"
    version = "3.1.404"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a60f3aaf910371ec56a1d32b6a1211e2ec8926742e31652acf40e61556b1a711"
    source = "https://download.visualstudio.microsoft.com/download/pr/5de23f6d-648c-455b-a7a9-d11c9a5bca40/4836262466f2d288e8ad8647944d062f/dotnet-sdk-3.1.405-linux-x64.tar.gz"
    source_sha256 = "28105c86ae24c12379b09a60c992e2f0daecea58cdd2ffa6a2e541fe26bf0661"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.405_linux_x64_any-stack_a60f3aaf.tar.xz"
    version = "3.1.405"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "d33b9ac219ede6f126cba02669e2833ee8b804dae5bf5c911de87d7deb5ed632"
    source = "https://download.visualstudio.microsoft.com/download/pr/820db713-c9a5-466e-b72a-16f2f5ed00e2/628aa2a75f6aa270e77f4a83b3742fb8/dotnet-sdk-5.0.100-linux-x64.tar.gz"
    source_sha256 = "b8278fd20a7242e711ee46910c23804babf9b38a4c1b97e2a4d9c5155d21cbd2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.100_linux_x64_any-stack_d33b9ac2.tar.xz"
    version = "5.0.100"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "1cc4e57c70727149d1772b90be1ace8134c2ac138b210425c909199ca98c9536"
    source = "https://download.visualstudio.microsoft.com/download/pr/a0487784-534a-4912-a4dd-017382083865/be16057043a8f7b6f08c902dc48dd677/dotnet-sdk-5.0.101-linux-x64.tar.gz"
    source_sha256 = "23df1eca7eb1302dfb10f4edce7edf7150e57698576f61b2dcb777c833cbd80c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.101_linux_x64_any-stack_1cc4e57c.tar.xz"
    version = "5.0.101"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.22"
    sdks = ["2.1.810"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.23"
    sdks = ["2.1.811"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.9"
    sdks = ["3.1.403"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.10"
    sdks = ["3.1.404"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.0"
    sdks = ["5.0.100"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.1"
    sdks = ["5.0.101"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
