api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "90bf09567f3a97774648f5965f01b149d62d83c0e745cac41c1fa662388b497b"
    source = "https://download.visualstudio.microsoft.com/download/pr/a3d67819-aa9d-4258-a19b-e5933c18d8b6/7fdd9609d50f6e4af6551983ff0b32d3/dotnet-sdk-2.1.808-linux-x64.tar.gz"
    source_sha256 = "5ea5a29cedeac170752fc1736e257cfdeffa7b3ccdc046fafb707c1b36cd1d36"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.808_linux_x64_any-stack_90bf0956.tar.xz"
    version = "2.1.808"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "849799474b03d2f722170bf2fff6dc8bb08ca4ebc10c86774559f9d1a4deb1bc"
    source = "https://download.visualstudio.microsoft.com/download/pr/a44fb0b1-2c91-41d6-8970-321872341326/7e150d5bc0d3d96ae8c7cbd9e6b890fe/dotnet-sdk-2.1.809-linux-x64.tar.gz"
    source_sha256 = "0c79f6133aa3394b683978774e0975122cd9d58b90c3b0b65bba48d44f5bafc0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.809_linux_x64_any-stack_84979947.tar.xz"
    version = "2.1.809"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "94ec0b48b052227519386233aeb84521440753951bbba6713702918bf6d71012"
    source = "https://download.visualstudio.microsoft.com/download/pr/4f9b8a64-5e09-456c-a087-527cfc8b4cd2/15e14ec06eab947432de139f172f7a98/dotnet-sdk-3.1.401-linux-x64.tar.gz"
    source_sha256 = "292d8f5694df7560c39a16c12d5b5efa4038c0973d1adb768f90f39982da1c43"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.401_linux_x64_any-stack_94ec0b48.tar.xz"
    version = "3.1.401"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "e0aedde79c13a4a58e0fb85dc7d12fe005675a4214bec009680d412981ece15a"
    source = "https://download.visualstudio.microsoft.com/download/pr/f01e3d97-c1c3-4635-bc77-0c893be36820/6ec6acabc22468c6cc68b61625b14a7d/dotnet-sdk-3.1.402-linux-x64.tar.gz"
    source_sha256 = "2b6b172f9483e499141e37a6b932a547d9476bf03f3e71a0fefb76c52e01a9ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.402_linux_x64_any-stack_e0aedde7.tar.xz"
    version = "3.1.402"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.20"
    sdks = ["2.1.808"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.21"
    sdks = ["2.1.809"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.7"
    sdks = ["3.1.401"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.8"
    sdks = ["3.1.402"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
