api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET Core SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-sdk = "5.*"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "5ead72ec6566910e493ccb3bf5d688f40861db9d50baf3cfaa13c9956d136ef9"
    source = "https://download.visualstudio.microsoft.com/download/pr/98903dda-7825-47af-9699-ac44f7f92cb6/7b5b7d7498bd2bc104510c14cb03342d/dotnet-sdk-2.1.812-linux-x64.tar.gz"
    source_sha256 = "98b306edbe4c1e6830085158117bb9680304709d6fca9a1c8e3b6db5274ecdce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.812_linux_x64_any-stack_5ead72ec.tar.xz"
    version = "2.1.812"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "8f9246c099362d8db7b79660b417d0ccb35e950bab3835534f90c8c14c9b778e"
    source = "https://download.visualstudio.microsoft.com/download/pr/e1883c23-aad6-4658-a0bf-cdfb3d430d26/a2b8bdd775b9f5b1ff3424463955001c/dotnet-sdk-2.1.813-linux-x64.tar.gz"
    source_sha256 = "75075c795104798ed8e57f3843238275c463f5537da919413da956ad77e898ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.813_linux_x64_any-stack_8f9246c0.tar.xz"
    version = "2.1.813"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "ee05431441441117af62a7816074cbe22507a10f50d7d51d7e85c3b2057a7c55"
    source = "https://download.visualstudio.microsoft.com/download/pr/d7b8da76-a160-44a1-8038-b4b91404b8f2/af410f6d2e213ef7ee9dfefd853e97c0/dotnet-sdk-3.1.406-linux-x64.tar.gz"
    source_sha256 = "9b436009f36e8e93f4414bfc245ad7c383521d95f80e8f6f12d93428bc186293"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.406_linux_x64_any-stack_ee054314.tar.xz"
    version = "3.1.406"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "d0142171d41b20d5a4e60f312119ff5fde94b9d8b0f54baa0a357104455ff24a"
    source = "https://download.visualstudio.microsoft.com/download/pr/ab82011d-2549-4e23-a8a9-a2b522a31f27/6e615d6177e49c3e874d05ee3566e8bf/dotnet-sdk-3.1.407-linux-x64.tar.gz"
    source_sha256 = "a744359910206fe657c3a02dfa54092f288a44c63c7c86891e866f0678a7e911"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.407_linux_x64_any-stack_d0142171.tar.xz"
    version = "3.1.407"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "a85dd2bdde1abb544d9c4d32ce0fd2f7fbc8ed21112c49269fa8cd13e99d2b92"
    source = "https://download.visualstudio.microsoft.com/download/pr/7f736160-9f34-4595-8d72-13630c437aef/b9c4513afb0f8872eb95793c70ac52f6/dotnet-sdk-5.0.102-linux-x64.tar.gz"
    source_sha256 = "4bb7f951750e87dffdbca5ee21d13b11e2db7f7e37045e84cd6052ff1fadd0aa"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.102_linux_x64_any-stack_a85dd2bd.tar.xz"
    version = "5.0.102"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "9ced70354622969af9575943ce31eadc21a61976b94ec5acce306e2834e4188f"
    source = "https://download.visualstudio.microsoft.com/download/pr/64a6b4b9-a92e-4efc-a588-569d138919c6/a97f4be78d7cc237a4f5c306866f7a1c/dotnet-sdk-5.0.200-linux-x64.tar.gz"
    source_sha256 = "fb1ffda1f49f5df846c155e1a5b436c90fe5f83a864093a93340c4fb068828cf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.200_linux_x64_any-stack_9ced7035.tar.xz"
    version = "5.0.200"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.24"
    sdks = ["2.1.812"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.25"
    sdks = ["2.1.813"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.12"
    sdks = ["3.1.406"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.13"
    sdks = ["3.1.407"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.2"
    sdks = ["5.0.102"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.3"
    sdks = ["5.0.200"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
