api = "0.2"

[buildpack]
  id = "paketo-buildpacks/dotnet-core-sdk"
  name = "Paketo .NET Core SDK Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-sdk"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    dotnet-sdk = "5.*"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "8a61800f5eed6c88e0f3addd30dc5d7cb8918500f67c6fa2a842724fe4d950e6"
    source = "https://download.visualstudio.microsoft.com/download/pr/7fba29f6-aac9-4b53-a5f9-9b421bec6288/70ac39be0282331d18b535f64ea5f40a/dotnet-sdk-2.1.815-linux-x64.tar.gz"
    source_sha256 = "72d2630b67c1337aa25285da82d1b0ce5eceb3e6cfabdb12521151fd4508c626"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.815_linux_x64_any-stack_8a61800f.tar.xz"
    version = "2.1.815"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "c4973b3fd3d7135a8fe558aca95b49c95da7aa1055193dfee624e47572ac87d1"
    source = "https://download.visualstudio.microsoft.com/download/pr/745ce65b-e1b7-442d-aebf-8fe18c4fceba/73d02f94e66602d4b6531b0b2003c798/dotnet-sdk-2.1.816-linux-x64.tar.gz"
    source_sha256 = "ff9969ea81ccef3ac4d721b122e030f7eaaedddcb45e295cc2aa73634f20d45e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.816_linux_x64_any-stack_c4973b3f.tar.xz"
    version = "2.1.816"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "fe050bf48d4def571764d8499858b688afa586d9966fdad725b2efbc2d4220a0"
    source = "https://download.visualstudio.microsoft.com/download/pr/dfbc47b7-4c2c-4e00-989e-a18f6f2e8fe8/5f42a60705fd9122837c68dcbdbbe278/dotnet-sdk-3.1.409-linux-x64.tar.gz"
    source_sha256 = "e0f4b47533bbf7529e3d9b1239ebf37ff8f332a4a056978131ed30bde0b8cd55"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.409_linux_x64_any-stack_fe050bf4.tar.xz"
    version = "3.1.409"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "4e29959ab9542721a45fcbdb7d746919ed04202b36a1ffecf83a2f2ab9715c93"
    source = "https://download.visualstudio.microsoft.com/download/pr/e6ae53a9-8567-4f44-b6ce-684d4f4a0b27/e0c29635c1c2ae9424390a41fecc95f1/dotnet-sdk-3.1.410-linux-x64.tar.gz"
    source_sha256 = "375f071439956f841ffe2c5c004d405b6b998c5793b1551c8695b963d402b804"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_3.1.410_linux_x64_any-stack_4e29959a.tar.xz"
    version = "3.1.410"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "6ff9d3ab2cca769e4dc436569871e031eb87482619be4c0bae212af9e24d758a"
    source = "https://download.visualstudio.microsoft.com/download/pr/5f0f07ab-cd9a-4498-a9f7-67d90d582180/2a3db6698751e6cbb93ec244cb81cc5f/dotnet-sdk-5.0.202-linux-x64.tar.gz"
    source_sha256 = "d2994d4e995bbab003b2d1b137807936fd96c94ba9982822893d62904aab54cf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.202_linux_x64_any-stack_6ff9d3ab.tar.xz"
    version = "5.0.202"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "6016e188974c530cbcfda90feaf2acf5f45dd71f1199b95ab366be33e53c0b51"
    source = "https://download.visualstudio.microsoft.com/download/pr/ef13f9da-46dc-4de9-a05e-5a4c20574189/be95913ebf1fb6c66833ca40060d3f65/dotnet-sdk-5.0.203-linux-x64.tar.gz"
    source_sha256 = "096ae3102c4d6759b87e97e466916a3f6ed0d85f18dc0e9d5c31f81e7bc7e94c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.203_linux_x64_any-stack_6016e188.tar.xz"
    version = "5.0.203"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "b7beea36213b341a5ebbcd84b42a1a870279bd3c8f6b77ce24902cea54aabb55"
    source = "https://download.visualstudio.microsoft.com/download/pr/e1c236ec-c392-4eaa-a846-c600c82bb7f6/b13bd8b69f875f87cf83fc6f5457bcdf/dotnet-sdk-5.0.301-linux-x64.tar.gz"
    source_sha256 = "3551215f7723cf9d262374ee3e7b83a4cd3a0ccaa1fa0b5decaf67c0ea054448"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_5.0.301_linux_x64_any-stack_b7beea36.tar.xz"
    version = "5.0.301"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.27"
    sdks = ["2.1.815"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.28"
    sdks = ["2.1.816"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.15"
    sdks = ["3.1.409"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.16"
    sdks = ["3.1.410"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.5"
    sdks = ["5.0.202"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "5.0.6"
    sdks = ["5.0.203"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
